### ISSUE TITLE
tagfield argument seems wrong - replacement branch is available but undocumented / patched

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-blog#220]
Hi @tractorcow  et al.

I am looking at https://github.com/silverstripe/silverstripe-blog/blob/master/code/model/BlogPost.php#L179.  It appears that the third argument for the tag-field is a map of categories.  That makes perfect sense to me.... BUT the tag field takes different arguments:

https://github.com/silverstripe-labs/silverstripe-tagfield/blob/master/code/TagField.php#L109

I see that this has been fixed here:
https://github.com/silverstripe-labs/silverstripe-tagfield/blob/tractorcow-patch-1/code/TagField.php#L28

but this is not documented anywhere (or patched!). 

What do you suggest?  We are keen to use this blog module.

Cheers

Nicolaas

**Comment by assertchris** [comment]
Hey Nicolaas,

The 2.0 beta of Blog is using the `develop` branch of TagField. The `develop` branch of TagField has a new API and the API has not yet settled (which is why we haven't tagged a stable version yet). We're gathering feedback during the Blog beta, and fixing bugs. The new API for TagField will be finalised, a new, stable version will be tagged and there will be documentation before Blog 2.0 leaves beta.

In the meantime, check out the `develop` branch's test to see how the new TagField is called. Please bare in mind that the API might still change.

Kind regards
Chris

**Comment by assertchris** [comment]
Fixed in https://github.com/silverstripe/silverstripe-blog/pull/253
