### ISSUE TITLE
URL Segment field and Menu title are missing from UI.

### ISSUE THREAD

**Issue by pitchandtone** [silverstripe/silverstripe-blog#273]
Seems like someone tried to push them into the post options panel but they're not actually being displayed there.

**Comment by pitchandtone** [comment]
![screen shot 2015-06-12 at 12 44 42 pm](https://cloud.githubusercontent.com/assets/1055059/8121511/d2df5a6e-1100-11e5-94d9-fb20aef8c1b1.png)

**Comment by assertchris** [comment]
It appears Menu Title has intentionally been hidden, and I am seeing URL segment:

![screen shot 2015-06-18 at 12 29 37 am](https://cloud.githubusercontent.com/assets/200609/8206861/2fa9724e-1551-11e5-9af1-934d9a608181.png)

**Comment by micmania1** [comment]
The reason MenuTitle was removed from the UI is because that as a blog post, it doesn't really belong in a menu. My understanding/interpretation of its usage is that its used in navigation and sidebar menu's.

I'm not against making it available again, but I would prefer it to be hidden by default.  If you need it in the current version, you should be able to re-add it with a DataExtension and hook into updateCMSFields..

I'm not sure why you're not seeing the url segment field - maybe another module or extension is conflicting (possibly translations)?

**Comment by micmania1** [comment]
There's been no movement on this for a while so i'm going to close it.
