### ISSUE TITLE
GridFieldCategorisationConfig - Performance issues when there are a lot of tags

### ISSUE THREAD

**Issue by quamsta** [silverstripe/silverstripe-blog#350]
We have a site with a lot of blog posts and tags (five years' worth of posts with around 3,000 tags!) we imported from Wordpress.

In the Blog class, the GridFieldCategorisationConfig component appears to load a "move to" dropdown that's populated with every tag in the db for each entry in GridField. Apparently $this->Tags() and $this->Categories() is called for each individual tag/category entry in the GridField to populate the dropdowns. This pegs our CPU at 99% for a long time and causes loading the Blog page in SilverStripe to be very slow.

Removing the GridFieldCategorisationConfig component from the Tags/Categories field in Blog speeds up the blog drastically. Caching all of the tags/categories first and loading them for all subsequent dropdowns might help, or somehow lazily loading the "Move to" dropdowns might help too.

**Comment by dhensby** [comment]
I'm not sure how 3,000 tags can be helpful for a blog reader are they really meant to look through 3,000 tags to find the tags they are interested in?

the Blog clearly isn't designed to work at that scale and I doubt it's a priority as 3k tags is pretty nuts.

Efficiency PRs will be accepted but I don't think it'll be a core focus for some time

**Comment by quamsta** [comment]
Just to make sure we're clear: this is 3,000 total tags from over 5+ years and 2,000 posts from a large music review and news blog. The issue is that when we view the Blog, the GridField populates each row with a dropdown that has a massive query for tags. 

What I'm hearing is that the blog module is not scalable to a degree that's useful for larger, longstanding projects and that "just don't have so much content" is the solution here. 

Not really very forward-thinking for a *content* management system, don't you think?

**Comment by stevie-mayhew** [comment]
An option is to replace those tag calls with the (silverstripe-select2)[https://github.com/sheadawson/silverstripe-select2] module. We use this in instances where there is a large number of things to be shown in a dropdown, such as members.

@dhensby would this be a good addition here? I think that with the work going on for 4.0 in FE that chosen will likely be moved out and a better system put in place, but for now this does fix the issue and I think is a good improvement. 

Its not a supported module though, so there might be some issues there.

**Comment by dhensby** [comment]
> this is 3,000 total tags from over 5+ years and 2,000 posts from a large music review and news blog

It doesn't matter how long it took or how many posts there are that doesn't mitigate a crap user experience - from a UX point of view 3,000 tags is not helpful for a user. Tags are there to help users find useful content, right? Who thinks making users search through 3k tags for their content is a good experience?

> What I'm hearing is that the blog module is not scalable to a degree that's useful for larger, longstanding projects

Correct

> "just don't have so much content" is the solution here

That's not my proposed solution but it is one. the solution is what you suggested, to make it more efficient, which is what I agreed with.

I stated that it's pretty clear that the blog isn't designed to work at the scale you're using it at - that's a statement of fact not an endorsement of crap code or inefficiency.

Efficiency PRs will be accepted but I don't think it'll be a core focus for some time. I assume that when you were scoping the work for your client you took into account how the blog module would handle the volume of content that they had and recommended appropriately as well as budgeting time to manage this problem and you don't expect someone else to fix this problem for you for free, right?

A PR to improve this aspect would be welcome, but it isn't a core focus at this time.

**Comment by dhensby** [comment]
@stevie-mayhew I'd try to avoid yet another dependency, but if select2 solves the problem quickly and easily, then yes - why not?

**Comment by dhensby** [comment]
> What I'm hearing is that the blog module is not scalable to a degree that's useful for larger, longstanding projects

Just to elaborate on this point - I'm pretty sure it's obvious that the SS blog module is not intended to be a WP killer or even comparable. It's pretty basic blog-ing functionality.

**Comment by tractorcow** [comment]
I think that this issue is more to do with gridfield / tagfield than blog per se.

We have had similar issues come up with large quantities of items being processed via a gridfield. E.g. AssetAdmin with > 30,000 files.

**Comment by tractorcow** [comment]
I've logged this in our internal bugtracker, and will see if we can come up with a solution for it.

**Comment by micmania1** [comment]
@quamsta do you have the forked version somewhere online that I can view? I'd be interested in seeing how you're disabling it.

One possibility could be to remove the dropdown from the GridField listing page and add something to the EditForm instead. I haven't had time to take a look at this yet but it should definitely be scalable.

I'd prefer to solve this without adding another configuration option if we can.

**Comment by dhensby** [comment]
> If the blog becomes unusable after a certain number of posts and tags, then there's something wrong. Something that needs to be checked out.

I completely agree. It needs fixing. But how OSS works is, "if there's a problem someone who it effects fixes it". Whilst no one at SilverStripe has this problem and no other dev (who's inclined to fix the problem) has the time or inclination to fix it, it won't get fixed. I'm not saying this to be unhelpful, it's because our time is limited like yours and so we can't fix all errors especially those that affect the minority of users.

> There's a bug with a large dataset and I thought I was doing right by reporting where I found the inefficiency in GridFieldCategorisationConfig.

You are. I'm sorry if it seems like I'm criticizing the bug report, I'm not. It needs fixing - I'm just being honest with you saying that it's unlikely to be fixed by the core team soon. What is going to have to happen is that a core team member will need to work on a project where we have 3k tags and then we'll realise it's crappy and fix it. We'd hope other users of our software would do the same.

> So you'll accept a pull request from me removing the MoveTo() functionality from the Blog Categories/Tags? Because we've internally forked and removed that functionality already and everything works fine

Possibly, though I'm not sure that's the right fix as it seems to simply hide the symptoms and not fix the problem. I also doubt a fork is needed to customise this, you'd likely be able to decorate the page type and remove the component from the gridfield or customise the CMSFields however you have done with your extension.

> Actually we're in the process of deciding whether or not to move the blog from its current CMS right now and this issue was brought up during the exploration, and we feel it's doable without the Categorisation "Move To" functionality.

OK - great - if you've found a work around that's acceptable then that's progress at least. Alerting us to the problem is important and then someone can fix it. Again, I'm just trying to be honest (rather than unhelpful) when I say it's not likely to be a priority.

> We're also considering investing in SilverStripe Platform, but we're not sure about that yet. I suppose it depends on the quality of response and support we get while we're checking it out.

There's a distinction between the OSS and the commercial products. Whilst I currently work for SilverStripe, I'm not paid to do OSS, that's another team, and so any time I spend on this is my own. This is my own "personal" support and not SilverStripe Ltd support, if you want that you can contact SilverStripe Ltd and enquire as to that. SS Platform does come with OSS issue support and resolution, so you can pay to have these issues fixed through the SSP service (included in some of the plans).

> My goal this year is to attempt to be contribute more to SilverStripe, since we've used it extensively since 2009. I'm just sort of dipping my toes into contributing bysubmitting issues, but I'm clearly not doing it right. Should I not submit something like this without a PR ready to go?

That's fantastic, we'd love as much contribution as possible and issue reporting is a valuable part of the open source process. Your issue is fine. I think the problem is my first comment was a bit too terse (apologies) which meant you thought my suggestion was to just "get rid of tags"; then when I said it's not a core focus you think that I was dismissing this report as unimportant.

The reality is that most core contributors work on this stuff in their own time or, if they need to fix a bug or add a feature for a paying client, they can fix a specific problem during work. Those that are paid to work on the OSS as their job are paid to work on the "[supported modules](https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/)" (of which this is one - see our [definition](https://www.silverstripe.org/software/addons/supported-modules-definition/)), but even then bugs need to be prioritised.

I can't speak for others but my impression is this will take a while to get a patch.

Luckily for you, though, @tractorcow (who is one of the nicest people in the world) thinks this is a more fundamental issue where even for paginated data sets in `gridfield`, logic is run against the whole list needlessly (rather than the segment we are displaying) and so has added it to the internal bug tracker to get looked at as it could have repercussions that are wider reaching than just the blog. If this is true, it'll likely be fixed slightly more quickly.

Please don't confuse my honesty of "it probably won't be looked at soon" or "it's not a priority" as dismissive or unhelpful, I'm being honest and straightforward so you don't get as annoyed when it's not fixed in 3 months

**Comment by quamsta** [comment]
Thanks for your replies, this has been helpful and educational. 

> @quamsta do you have the forked version somewhere online that I can view? I'd be interested in seeing how you're disabling it.

We don't have a fork up because I think we just commented out a couple lines in Blog.php, around lines 119-131. We simply commented out the lines where GridFieldCategorisationConfig::create() is called.

I'm not sure how we could decorate or efficiently subclass the Blog to achieve the same result, but it seems that would be preferable to maintaining a fork without the categorisation config.

```
$categories = GridField::create(
	'Categories',
	_t('Blog.Categories', 'Categories'),
	$self->Categories()
	//GridFieldCategorisationConfig::create(15, $self->Categories()->sort('Title'), 'BlogCategory', 'Categories', 'BlogPosts')
);

$tags = GridField::create(
	'Tags',
	_t('Blog.Tags', 'Tags'),
	$self->Tags()
	//GridFieldCategorisationConfig::create(15, $self->Tags()->sort('Title'), 'BlogTag', 'Tags', 'BlogPosts')
);
```

**Comment by tractorcow** [comment]
A brief look at GridFieldCategorisationConfig doesn't reveal any immediate clues;

Does the gridfield actually work efficiently with the default config, @quamsta ? Have you tested with other gridfield components? It would be interesting to see which ones are the "bad" ones that we could include in our performance testing. ;)

**Comment by quamsta** [comment]
I believe it has something to do with the second arguments for the GridFieldCategorisationConfig instantiation method, e.g.

`$self->Categories()->sort('Title')`

and

`$self->Tags()->sort('Title')`

My guess is that those arguments are being passed to another class (GridFieldMergeAction?) and looped over and over again for all visible rows in the GridField, and since we have so many tags/categories, everything blows up.

**Comment by micmania1** [comment]
It could be this line: https://github.com/silverstripe/silverstripe-blog/blob/0a8ee233a601f81f5264fbfbcc7e7c4c4b77ea32/code/admin/GridFieldMergeAction.php#L73

So we initially load 15 items (eg. Tags) into the GridField. **Each row** then loads all 3000 tags (3000 * 15) and loops through them (at least once per row) to display them in the dropdown.

**Comment by tractorcow** [comment]
Oh good spotting... ouch!

**Comment by micmania1** [comment]
@quamsta Can you test https://github.com/silverstripe/silverstripe-blog/pull/383 and see if it solves your problem?

I think it might still be too slow in which case I think the only option would be to disable this feature within the GridField for large sites and move it into the tag edit form.

**Comment by quamsta** [comment]
Sorry for the delay, yes it's still too slow to be usable with that many posts.

**Comment by micmania1** [comment]
So a few things learnt from my attempt:
1. Its still too slow
2. Dropdowns aren't useful after 20-30 records so this isn't really a good solution.
3. There's no way other than this to move to a new category or tag

My suggested solution:
We keep this as a feature, but remove the dropdown if there are less than `x` tags/categories - the limit can be configured by the config system. Setting 0 would disable the feature and it would default to 30 records.

The ability to move posts to another category should always exist on the edit form.

Any feedback?

**Comment by sekjal** [comment]
What about pulling out the call for all tags/categories into a function and using SS_Cache with it?  At the worst, you'd be cutting the number of calls down from the number of items per page to just one.  At best, if the list of tags/categories isn't updating as fast as the list of Blog Posts, then you'll get even more reuse out of the cached content.

This doesn't solve the UI problem with a dropdown and a large number of possibilities, but hopefully it would at least make performance acceptable for all other aspects of Blog Post management.

**Comment by micmania1** [comment]
@sekjal I had thought about that but you wouldn't be able to use SS_Cache because every dropdown is different (it excludes itself).

Essentially, what I tried to do was cache it in memory but I think (this is an assumption) the CPU issues were caused by looping so many records which is unavoidable even with cache as the template system is the thing that loops.

**Comment by tractorcow** [comment]
> @sekjal I had thought about that but you wouldn't be able to use SS_Cache because every dropdown is different (it excludes itself).

You could cache the global list and remove the own-item as a post-cache-retrieval step.

**Comment by maxime-rainville** [comment]
This won't affect SS4 because it nows uses the TagField witch rather than a plain DropDownField.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
