### ISSUE TITLE
SilverStripe 4.x compatibility

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-blog#405]
I've started work on this here: https://github.com/micmania1/silverstripe-blog/tree/ss4
- [x] API updated
- [x] Tests passing
- [ ] Update composer (including dependencies - use ss4 branches for now where available)
- [x] Move shared Tag/Category/URLSegment functionality into a trait and share on BlogTag and BlogCategory
- [x] Remove compass (in favour of gulp) for better future-proofing
- [ ] Test/Update to use SS4s new theme system
- [ ] Test/Update to ensure it works with SS4 namespace changes
- [ ] Remove code for old PHP version (eg. https://github.com/micmania1/silverstripe-blog/blob/ss4/code/model/Blog.php#L116)

Bugs:
- [x] Right sidebar - floats left instead of right (also hides bottom right preview options)
- [x] Right sidebar - update open/close icon at the bottom to float left when open
- [x] Tags & Categories listboxes not working
- [x] Add new blog post above gridfield takes you to 404 page

Blockers:
- [x] https://github.com/silverstripe/silverstripe-framework/issues/5625

Further Investigation/Ideas/Not Required:
- [ ] Should we implement namespacing in Blog? What effect will this have on upgrades?
- [ ] Should we remove migration scripts from v1 to v2 when v3 is released?
- [ ] Consider ways to extend page (see https://github.com/silverstripe/silverstripe-framework/issues/5844)

**Comment by micmania1** [comment]
ps. Can someone add a 3.x label please? It allows me to add milestones but not labels :/

**Comment by micmania1** [comment]
Branches where this work lives:
Blog: https://github.com/micmania1/silverstripe-blog/tree/ss4
Lumberjack: https://github.com/micmania1/silverstripe-lumberjack/tree/ss4
Tagfield: https://github.com/micmania1/silverstripe-tagfield/tree/ss4

**Comment by tractorcow** [comment]
Good job @micmania1 :D Sorry to break everything, but remember to update for namespacing. Ping me if you need help running the upgrade tool.

**Comment by sminnee** [comment]
@micmania1 can you:

 * raise PRs for your work in progress
 * put the to-do items 
 * give me write access to your micmania1 forks so I can push work there?

**Comment by robbieaverill** [comment]
Hey @micmania1, @sminnee and @tractorcow  - I'm working on this as part of a project upgrade at the moment. I've forked of from @micmania1's initial work - here's my status with blog and its dependencies:

## Completed

- [x] Composer aliases added for `3.0.x-dev` and
- [x] PSR-4 autoloading compatibility added
- [x] Namespacing done
- [x] Templates moved, tweaks and references made
- [x] Legacy class map added for ORM updates, and
- [x] Upgrader map added
- [x] Lumberjack completed as above
- [x] Tagfield completed as above

## Not completed

- [ ] Update blog fork from current master
- [ ] Old PHP code removed
- [ ] Comments compatibility
- [ ] Bug: The sidebar in admin isn't displaying correctly in the SS4 CMS context

Frontend assets haven't been thoroughly tested yet.

If someone can create a `3` branch in this module, and a `2` branch in silverstripe/tagfield and silverstripe/lumberjack then I'll raise an initial pull request for each of these changes so far.

I plan to continue to chip away at each of these as I continue with the project I'm upgrading. This will undoubtedly involve some more bug fixes.

It'd probably be good to set a baseline, so subsequent changes would be smaller and easily reviewable.

@micmania1 - I'd also like you to take a look over my changes in blog and lumberjack, since you're the one probably most familiar with these modules. Hopefully @tractorcow has some time to review the tagfield changes.

@sminnee if you want me to raise issues in those other two repos for SS4 compatibility and be a little more verbose than a comment here, I'm happy to do so.

## Changes to date

- [silverstripe/blog](https://github.com/silverstripe/silverstripe-blog/compare/master...robbieaverill:ss4?expand=1&w=1)
- [silverstripe/lumberjack](https://github.com/silverstripe/silverstripe-lumberjack/compare/master...robbieaverill:2?expand=1&w=1)
- [silverstripe/tagfield](https://github.com/silverstripe/silverstripe-tagfield/compare/master...robbieaverill:2?expand=1&w=1)

**Comment by micmania1** [comment]
@robbieaverill I'll take a look when I get the chance. One thing you will need to do is rebase against master as there's probably some changes since I started this.

**Comment by robbieaverill** [comment]
@micmania1 yeah I noticed that. I'll rebase it now and tidy up my commits a little.

**Comment by micmania1** [comment]
I'm going to close this as work has been continued in #421.
