### ISSUE TITLE
Need to add video feature and location field into the blog

### ISSUE THREAD

**Issue by buffy999** [silverstripe/silverstripe-blog#468]
Hi,

Is there a code that i can add the video feature into the blog? same way as the image feature? Prefer to have the host videos instead of using YouTube etc...

Also i need some code for to add the location/region field into the blog as well, couldn't find any where that i can use for the blog,

Thanks,
Kirsten

**Comment by robbieaverill** [comment]
Hey @buffy999, thanks for logging your issue.

Uploading/embedding videos:

* You can embed externally hosted videos easily, see https://www.youtube.com/watch?v=1mkI0H3J32Y and https://userhelp.silverstripe.org/en/3.6/creating_pages_and_content/creating_and_editing_content/inserting_media. It's probably better all round to host your videos externally rather than uploading them to your web server
* You could upload to our server and embed directly using another module, e.g. something like https://github.com/guru-digital/silverstripe-video-embed

Adding location/region field - this can be done in many different ways: adding a text field, tag field, relationship to other data models, etc. You'll need to develop this functionality in your project and add it into the blog module using [extensions](https://docs.silverstripe.org/en/developer_guides/extending/extensions/).

Hope this helps!

**Comment by buffy999** [comment]
Hi Robbie,

Ok thank you for the tips. I'll look into it about the videos.

I still don't know how to add the location/region script, i'm still not familiar with PHP codes at the moment, am still learning. I need some help on that if you don't mind?

**Comment by robbieaverill** [comment]
Hey @buffy999, you'd probably be best to join the SilverStripe community Slack channel and ask for some assistance there: silverstripe-users.signup.team

We try and keep GitHub repositories for tracking bug reports.
