### ISSUE TITLE
Positioning of Templates on SS4

### ISSUE THREAD

**Issue by mlewis-everley** [silverstripe/silverstripe-blog#503]
I think this is more of a question than an issue, but it is one I am finding perplexing.

It appears in the SS4 version of the blog, we need to add our Page templates in the following location:

- themes
  - mytheme
    - templates
      - SilverStripe
        - Blog
          - Model
            - Layout

Rather than the conventional:

- themes
  - mytheme
    - templates
      - Layout

I can understand why you would place module templates in a namespaced location, but is it not possible to also fall back to the conventional SilverStripe Page template location as well?

The problem is, on larger installs (with lots of modules), won't you end up with templates all over the place (lots of nested, empty folders with odd templates dotted about)?

I did ask about this on the ss4 slack channel and was told basically this is how SS4 does templating now, but I thought I would ask the developers/maintainers of this module if this is the case?

**Comment by robbieaverill** [comment]
Hey @mlewis-everley, thanks for raising the question.

You're right, templates in SilverStripe 4 live in the folder path that matches the fully qualified class name that they represent, including namespaces.

>is it not possible to also fall back to the conventional SilverStripe Page template location as well?

It is, and it should do that if no other templates are found for the page type. Page.ss will still live in the root templates folder, since we don't namespace the Page class.

>The problem is, on larger installs (with lots of modules), won't you end up with templates all over the place (lots of nested, empty folders with odd templates dotted about)?

You will end up with your templates in neatly organised folders, which match the namespaces for the classes that they belong to, yes 😄 the idea was that this would be preferable to having the same number of templates in one folder, or an arbitrary set of folders which each dev can conjure up. You shouldn't end up with empty folders because (a) git won't track empty folders (without encouragement) and (b) you only need to create folder structures to contain templates that you want to override or create new.

FYI, you can still use any template you want for a PHP class, you'd just specify something with `$this->renderWith(...)` - it'll default to the equivalent of `__CLASS__` otherwise.

This is the standard process for all SilverStripe 4 modules now, including custom user code by default. For more info, this might help: https://docs.silverstripe.org/en/4/developer_guides/templates/template_inheritance/

Cheers!

**Comment by mlewis-everley** [comment]
Thanks for the response @robbieaverill , I may be misunderstanding you, but do you mean the blog template should be able to be added to my templates/theme/layout directory and SilverStripe will still find it? If so, this is not happening?

I guess I didn't really mean empty folders, more masses of folders with only one sub folder in it (or one file). To be honest, I hadn't really considered what git was tracking, rather that it can be a bit of a pain having to navigate myriads of nested folders to try and find one template.

**Comment by robbieaverill** [comment]
Sorry, yes your first statement is correct, however the path would need to be either themes/therename/templates, mysite/templates or modulename/templates

**Comment by mlewis-everley** [comment]
Thanks for the reply @robbieaverill that is what I meant. So we have added `Blog.ss` in: `ourtheme/templates/Layout` and also tried `ourtheme/templates/Model/Layout` (I got the order wrong my previous message) but SilverStripe refused to see these templates. I this a bug in SS framework/CMS?

**Comment by robbieaverill** [comment]
@mlewis-everley please direct questions towards StackOverflow, the community Slack channel or the dev mailing list in future.

You need to use the class namespace, as explained in the documentation: https://docs.silverstripe.org/en/4/developer_guides/templates/template_inheritance/

In your case if would be `ourtheme/templates/SilverStripe/Blog/Model/Layout/Blog.ss`
