### ISSUE TITLE
Increase test coverage to cover archive loading

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-blog#516]
via a functional test.
This should catch issues caused by e.g. Month 39 being requested via the URL as per the fix in #515

**Comment by robbieaverill** [comment]
The part where this code is used is in a template. It's in blog by default by disabled in the CWP starter theme by default. I think a simple unit test would suffice for this particular example.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-blog/pull/575

I considered changing the date for day formatting so it would return `01` instead of `1` but didn't because it'd probably be a breaking change. There's a bit of low hanging refactor fruit in the next major version bump for this module though.
