### ISSUE TITLE
.upgrade.yml namespace error for BlogController and BlogPostController

### ISSUE THREAD

**Issue by stevevu** [silverstripe/silverstripe-blog#555]
Hi,

v3.2.1 .upgrade.yml incorrectly specifies that BlogController and BlogPostController belong in the `Silverstripe\Blog\Controllers` namespace when they are actually in the `SilverStripe\Blog\Model` namespace.

This will cause issues when using the SilverStripe SS3 to SS4 Upgrade module and existing code decorates BlogController or BlogPostController.  So for example, if I have an Extension for BlogController, the upgrade module will update my YML config to be:

```
SilverStripe\Blog\Controllers\BlogController:
  extensions:
    - QI\App\Extension\BlogExtensionController
```

when it should be:

```
SilverStripe\Blog\Model\BlogController:
  extensions:
    - QI\App\Extension\BlogExtensionController
```

Then any code in my BlogExtensionController class never gets called.  Surprisingly, dev/build doesn't complain about this.

Fix is simple:

update lines 12,13:

```
Blog_Controller: SilverStripe\Blog\Controllers\BlogController
BlogController: SilverStripe\Blog\Controllers\BlogController
```

to:
```
BlogController: SilverStripe\Blog\Model\BlogController
```
(can delete the Blog_Controller record since this may be the old classname)

update lines 16,17:
```
BlogPost_Controller: SilverStripe\Blog\Controllers\BlogPostController
BlogPostController: SilverStripe\Blog\Controllers\BlogPostController
```
to:
```
BlogPostController: SilverStripe\Blog\Controllers\BlogPostController
```
(can delete the BlogPost_Controller record since this may be the old classname)

thanks!

**Comment by NightJar** [comment]
Hi @stevevu thanks for reporting :)

It's unfortunate this has happened, but I gather it's likely because as Blogs are still Page types, there still exists minor coupling in that the model and controller need to exist in the same namespace (which is why the broken namespace in .upgrade.yml makes more sense, logically).

Your points are all spot on, except I think that `BlogPost_Controller` and `Blog_Controller` should remain in the `.upgrade.yml` as they are still valid legacy model names, depending on what version someone is upgrading from. It's OK to have more than one mapping for a new class name.

It sounds like you've got it well worked out, how would you feel about submitting a pull request to patch this?

**Comment by robbieaverill** [comment]
Fixed with a cherry-pick in https://github.com/silverstripe/silverstripe-blog/pull/557 and 682e522

Thanks @stevevu
