### ISSUE TITLE
$MinutesToRead is not working in other languages

### ISSUE THREAD

**Issue by Misagh90** [silverstripe/silverstripe-blog#567]
Hi, 
The `$MinutesToRead` not working on Persian(Farsi), Hebrew & ..., and only shown the "Less than a minute to read".

**Comment by NightJar** [comment]
Hi @Misagh90 I see you've closed this yourself, I'm not sure if that was intentional, but for the record in case any one else comes accross this issue, we use Transifex to maintain translations, which you can read more about in the documentation:
https://docs.silverstripe.org/en/4/contributing/translations/

If you'd like to help out with adding translations for a particular (set of) languages, please feel free to contribute on Transifex. In this case `MinutesToRead` has been a recent feature added, and is likely in need of translation to many languages :)

If there is an existing translation, feel free to [open an issue to update the translations](https://github.com/silverstripe/silverstripe-blog/issues/565) and a maintainer can do this for you.

**Comment by Misagh90** [comment]
I try my translation in template for these. 
First i put some lorem ipsum for these languages and show me the less than a minute, after that i typed some paragraph and i saw that the reading time change so i closed this issue.

**Comment by NightJar** [comment]
Transifex is a solution in itself, if you create an account you should be able to access and propose changes for the SilverStripe-blog module through the web interface. At that point a maintainer can accept it, and it will be updated with the next release :)

https://www.transifex.com/silverstripe/silverstripe-blog/
