### ISSUE TITLE
Page crash when creating a new blog post

### ISSUE THREAD

**Issue by jamesanstee** [silverstripe/silverstripe-blog#592]
We currently upload a blog post every day giving an update on the day's news, recently when trying to do this, the page has been crashing. This means that for every post we have to add the title, save and publish, the page crashes we then close the page, open it again and enter the next field. We then have to do the same process for every field massively slowing down the process and delaying our daily post. This has only started to happen over the last few weeks and we had no problem before. Any suggestions?

**Comment by robbieaverill** [comment]
Hi @jamesanstee, we'll need more details on your set up in order to help fix your problem. How many fields do you have on your blog post, how many blogs and blog posts do you have in your database, which version of SilverStripe are you running, etc

**Comment by NightJar** [comment]
To get the base information about the versions in use, you can run `composer show` - this will give you a list of all the modules installed on your site and at what version.
We're interested in the framework, cms, and blog modules in particular here.
You can use grep to filter by `silverstripe` if you'd like :)

**Comment by jamesanstee** [comment]
The website uses SilverStripe version 3.5.3, and uses very few additional modules. We have around 170 blog posts on the website in total across 4 different blogs. The majority of the blog posts are housed in one field, around 150 of them. In terms of fields on a blog post it is around 10 or 11. Hope this added information helps.

**Comment by NightJar** [comment]
Thanks for the extra info @jamesanstee - unfortunately this version is very old, and I would encourage you to upgrade the site at your earliest convenience, to receive bug fixes and important security patches.

If you are still experiencing this issue with the newer version, feel free to respond to this issue and we'll re-open to investigate.

From the top of my head though this issue is very strange, and I cannot think of anything that might cause it. A page once loaded is generally static - I don't know what might cause it to crash (nor in what manner - do you mean the browser? have you tried others?).

In your position, I would start by getting your development team to look into what requests or other activities are happening in the background - I don't believe there is anything in the blog module that might cause this. This sounds like a job best looked at by the development team working on your site - as it is likely caused by integration issues with other functionality added to the site.

If you or anyone else is able to give more info, please do.
I really appreciate the time you've taken to give this feedback, but I'm afraid I'm going to have to close this due to the age of the installation, the nature of the issue with insufficient information to proceed.
As mentioned before though, if you've more info you can share (perhaps a screen recording or a series of screenshots) to help convey the issue as it presents itself, then someone may be able to help.

# Closing a SilverStripe 3 issue

Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
